# This is a basic workflow to help you get started with Actions

name: Azure Python 3.7
# Controls when the workflow will run
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Set up Python 3.7.3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.3
      - name: Install depencencies
        run: |
          make install
      - name: Lint
        run: |
          make Lint
      - name: Test
        run: |
          make test
      
